//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CrackerModel", "FK_Transactions_Bugs", "Bug", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CrackerModel.Bug), "Transaction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CrackerModel.Transaction), true)]
[assembly: EdmRelationshipAttribute("CrackerModel", "FK_Transactions_Languages", "Language", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CrackerModel.Language), "Transaction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CrackerModel.Transaction), true)]
[assembly: EdmRelationshipAttribute("CrackerModel", "FK_Transactions_Statuses", "Status", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CrackerModel.Status), "Transaction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CrackerModel.Transaction), true)]

#endregion

namespace CrackerModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CrackerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CrackerEntities object using the connection string found in the 'CrackerEntities' section of the application configuration file.
        /// </summary>
        public CrackerEntities() : base("name=CrackerEntities", "CrackerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CrackerEntities object.
        /// </summary>
        public CrackerEntities(string connectionString) : base(connectionString, "CrackerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CrackerEntities object.
        /// </summary>
        public CrackerEntities(EntityConnection connection) : base(connection, "CrackerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Language> Languages
        {
            get
            {
                if ((_Languages == null))
                {
                    _Languages = base.CreateObjectSet<Language>("Languages");
                }
                return _Languages;
            }
        }
        private ObjectSet<Language> _Languages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Status> Statuses
        {
            get
            {
                if ((_Statuses == null))
                {
                    _Statuses = base.CreateObjectSet<Status>("Statuses");
                }
                return _Statuses;
            }
        }
        private ObjectSet<Status> _Statuses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bug> Bugs
        {
            get
            {
                if ((_Bugs == null))
                {
                    _Bugs = base.CreateObjectSet<Bug>("Bugs");
                }
                return _Bugs;
            }
        }
        private ObjectSet<Bug> _Bugs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Transaction> Transactions
        {
            get
            {
                if ((_Transactions == null))
                {
                    _Transactions = base.CreateObjectSet<Transaction>("Transactions");
                }
                return _Transactions;
            }
        }
        private ObjectSet<Transaction> _Transactions;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Languages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLanguages(Language language)
        {
            base.AddObject("Languages", language);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Statuses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStatuses(Status status)
        {
            base.AddObject("Statuses", status);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bugs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBugs(Bug bug)
        {
            base.AddObject("Bugs", bug);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Transactions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTransactions(Transaction transaction)
        {
            base.AddObject("Transactions", transaction);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CrackerModel", Name="Bug")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bug : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bug object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="bug1">Initial value of the Bug1 property.</param>
        public static Bug CreateBug(global::System.Int32 id, global::System.String bug1)
        {
            Bug bug = new Bug();
            bug.Id = id;
            bug.Bug1 = bug1;
            return bug;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Bug1
        {
            get
            {
                return _Bug1;
            }
            set
            {
                OnBug1Changing(value);
                ReportPropertyChanging("Bug1");
                _Bug1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Bug1");
                OnBug1Changed();
            }
        }
        private global::System.String _Bug1;
        partial void OnBug1Changing(global::System.String value);
        partial void OnBug1Changed();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CrackerModel", "FK_Transactions_Bugs", "Transaction")]
        public EntityCollection<Transaction> Transactions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transaction>("CrackerModel.FK_Transactions_Bugs", "Transaction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transaction>("CrackerModel.FK_Transactions_Bugs", "Transaction", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CrackerModel", Name="Language")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Language : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Language object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="languageLong">Initial value of the LanguageLong property.</param>
        /// <param name="languageShort">Initial value of the LanguageShort property.</param>
        public static Language CreateLanguage(global::System.Int32 id, global::System.String languageLong, global::System.String languageShort)
        {
            Language language = new Language();
            language.ID = id;
            language.LanguageLong = languageLong;
            language.LanguageShort = languageShort;
            return language;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LanguageLong
        {
            get
            {
                return _LanguageLong;
            }
            set
            {
                OnLanguageLongChanging(value);
                ReportPropertyChanging("LanguageLong");
                _LanguageLong = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LanguageLong");
                OnLanguageLongChanged();
            }
        }
        private global::System.String _LanguageLong;
        partial void OnLanguageLongChanging(global::System.String value);
        partial void OnLanguageLongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LanguageShort
        {
            get
            {
                return _LanguageShort;
            }
            set
            {
                OnLanguageShortChanging(value);
                ReportPropertyChanging("LanguageShort");
                _LanguageShort = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LanguageShort");
                OnLanguageShortChanged();
            }
        }
        private global::System.String _LanguageShort;
        partial void OnLanguageShortChanging(global::System.String value);
        partial void OnLanguageShortChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CrackerModel", "FK_Transactions_Languages", "Transaction")]
        public EntityCollection<Transaction> Transactions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transaction>("CrackerModel.FK_Transactions_Languages", "Transaction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transaction>("CrackerModel.FK_Transactions_Languages", "Transaction", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CrackerModel", Name="Status")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Status : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Status object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="statusName">Initial value of the StatusName property.</param>
        public static Status CreateStatus(global::System.Int32 id, global::System.String statusName)
        {
            Status status = new Status();
            status.Id = id;
            status.StatusName = statusName;
            return status;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StatusName
        {
            get
            {
                return _StatusName;
            }
            set
            {
                OnStatusNameChanging(value);
                ReportPropertyChanging("StatusName");
                _StatusName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StatusName");
                OnStatusNameChanged();
            }
        }
        private global::System.String _StatusName;
        partial void OnStatusNameChanging(global::System.String value);
        partial void OnStatusNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CrackerModel", "FK_Transactions_Statuses", "Transaction")]
        public EntityCollection<Transaction> Transactions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transaction>("CrackerModel.FK_Transactions_Statuses", "Transaction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transaction>("CrackerModel.FK_Transactions_Statuses", "Transaction", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CrackerModel", Name="Transaction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Transaction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Transaction object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="bugId">Initial value of the BugId property.</param>
        /// <param name="statusId">Initial value of the StatusId property.</param>
        /// <param name="changedBy">Initial value of the ChangedBy property.</param>
        /// <param name="changedOn">Initial value of the ChangedOn property.</param>
        /// <param name="languageId">Initial value of the LanguageId property.</param>
        public static Transaction CreateTransaction(global::System.Int32 id, global::System.Int32 bugId, global::System.Int32 statusId, global::System.String changedBy, global::System.DateTime changedOn, global::System.Int32 languageId)
        {
            Transaction transaction = new Transaction();
            transaction.Id = id;
            transaction.BugId = bugId;
            transaction.StatusId = statusId;
            transaction.ChangedBy = changedBy;
            transaction.ChangedOn = changedOn;
            transaction.LanguageId = languageId;
            return transaction;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BugId
        {
            get
            {
                return _BugId;
            }
            set
            {
                OnBugIdChanging(value);
                ReportPropertyChanging("BugId");
                _BugId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BugId");
                OnBugIdChanged();
            }
        }
        private global::System.Int32 _BugId;
        partial void OnBugIdChanging(global::System.Int32 value);
        partial void OnBugIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StatusId
        {
            get
            {
                return _StatusId;
            }
            set
            {
                OnStatusIdChanging(value);
                ReportPropertyChanging("StatusId");
                _StatusId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusId");
                OnStatusIdChanged();
            }
        }
        private global::System.Int32 _StatusId;
        partial void OnStatusIdChanging(global::System.Int32 value);
        partial void OnStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ChangedBy
        {
            get
            {
                return _ChangedBy;
            }
            set
            {
                OnChangedByChanging(value);
                ReportPropertyChanging("ChangedBy");
                _ChangedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ChangedBy");
                OnChangedByChanged();
            }
        }
        private global::System.String _ChangedBy;
        partial void OnChangedByChanging(global::System.String value);
        partial void OnChangedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ChangedOn
        {
            get
            {
                return _ChangedOn;
            }
            set
            {
                OnChangedOnChanging(value);
                ReportPropertyChanging("ChangedOn");
                _ChangedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChangedOn");
                OnChangedOnChanged();
            }
        }
        private global::System.DateTime _ChangedOn;
        partial void OnChangedOnChanging(global::System.DateTime value);
        partial void OnChangedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LanguageId
        {
            get
            {
                return _LanguageId;
            }
            set
            {
                OnLanguageIdChanging(value);
                ReportPropertyChanging("LanguageId");
                _LanguageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LanguageId");
                OnLanguageIdChanged();
            }
        }
        private global::System.Int32 _LanguageId;
        partial void OnLanguageIdChanging(global::System.Int32 value);
        partial void OnLanguageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TimeSpent
        {
            get
            {
                return _TimeSpent;
            }
            set
            {
                OnTimeSpentChanging(value);
                ReportPropertyChanging("TimeSpent");
                _TimeSpent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeSpent");
                OnTimeSpentChanged();
            }
        }
        private Nullable<global::System.Int32> _TimeSpent;
        partial void OnTimeSpentChanging(Nullable<global::System.Int32> value);
        partial void OnTimeSpentChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CrackerModel", "FK_Transactions_Bugs", "Bug")]
        public Bug Bug
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bug>("CrackerModel.FK_Transactions_Bugs", "Bug").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bug>("CrackerModel.FK_Transactions_Bugs", "Bug").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bug> BugReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bug>("CrackerModel.FK_Transactions_Bugs", "Bug");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bug>("CrackerModel.FK_Transactions_Bugs", "Bug", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CrackerModel", "FK_Transactions_Languages", "Language")]
        public Language Language
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("CrackerModel.FK_Transactions_Languages", "Language").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("CrackerModel.FK_Transactions_Languages", "Language").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Language> LanguageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("CrackerModel.FK_Transactions_Languages", "Language");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Language>("CrackerModel.FK_Transactions_Languages", "Language", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CrackerModel", "FK_Transactions_Statuses", "Status")]
        public Status Status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("CrackerModel.FK_Transactions_Statuses", "Status").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("CrackerModel.FK_Transactions_Statuses", "Status").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Status> StatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("CrackerModel.FK_Transactions_Statuses", "Status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Status>("CrackerModel.FK_Transactions_Statuses", "Status", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
